issues:
  max-same-issues: 0
  max-issues-per-linter: 0
linters:
  presets: 
  - bugs
  - error
  - format
  - performance
  - unused
  enable:
  - goconst
  - gocritic
  - gocyclo
  - gofmt
  - gomnd
  - goprintffuncname
  - gosimple
  - lll
  - misspell
  - nakedret
  - promlinter
  - revive
linters-settings:
  lll:
    line-length: 200
